version: 2
jobs:
  build:
    working_directory: /go/src/github.com/grugrut/newsales-viewer
    docker:
      - image: mercari/appengine-go
    steps:
      - checkout
      - run:
          name: prepare npm
          command: |
          curl -sL https://deb.nodesource.com/setup_8.x | bash -
          apt-get install -y nodejs
          npm install -g npm
      - run:
          name: prepare golang tools
          command: |
            go get github.com/golang/lint/golint
            go get -u github.com/golang/dep/cmd/dep
      - run:
          name: retrieve dependencies
          command: |
            npm install
            dep ensure -v
      - run:
          name: test
          command: |
            go vet ./...
            go list ./... | xargs golint -set_exit_status
            go test ./...
            ./node_modules/.bin/eslint front
      - run:
          name: webpack
          command: ./node_modules/.bin/webpack
      - run:
          name: deploy
          command: |
            echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            appcfg.py update --application ${PROJECT_ID} --oauth2_access_token=$(gcloud auth print-access-token 2> /dev/null) app/app.yaml
            appcfg.py update_cron --application ${PROJECT_ID} --oauth2_access_token=$(gcloud auth print-access-token 2> /dev/null) app

