version: 2
jobs:
  build:
    working_directory: /go/src/github.com/grugrut/newsales-viewer
    docker:
      - image: mercari/appengine-go
    steps:
      - checkout
      - run:
          command: go get github.com/golang/lint/golint
      - run: |
          go get -u github.com/golang/dep/cmd/dep
          dep ensure -v
      - run:
          command: go vet ./...
      - run:
          command: go list ./... | xargs golint -set_exit_status
      - run:
          command: go test ./...
      - run:
          name: Store Service Account
          command: echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json
      - run: |
          gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          appcfg.py update --application ${PROJECT_ID} --oauth2_access_token=$(gcloud auth print-access-token 2> /dev/null) app/app.yaml 
